### ISSUE TITLE
The property 'PartitionNumber' cannot be found on this object

### ISSUE THREAD

**Issue by SirMoefe** [FSLogix/Invoke-FslShrinkDisk#18]
Dear Jim

Thanks for providing this amazing script! 
In my enviroment it's sadly mostly not working. I always get the following error:
**"Failed to create junction point to - ""The property 'PartitionNumber' cannot be found on this object. Verify that the property exists.**

I looked through the script and noticed, the partitiontype of the partitions that is selected should be 'Basic'.

I manualy mounted a vhdx file and checked the partitiontype and it turned out that my partitiontype is 'IFS'
We used UPM before and I created the vhdx files with a script and copied all the content of the UPM profiles into the vhdx. Maybe that's why... 

I changed the Value for the partition from 'Basic' to 'IFS' in the script and tested again. Sadly I still get the same error...

I again did all the steps manualy and I received the correct value for the 'PartitionNumber' property.

Do you have any idea, why it is not working, when I run script?

Thanks in advance!

Patrick

**Comment by JimMoyle** [comment]
Hi @SirMoefe,

I'm afraid I only support disks created by FSLogix rather than other disks.  You are the second person who has come to me with this, so I'll consider it for the future.

In the meantime there is a branch which has code which might catch your problem  Can you re-download from this branch:

https://github.com/FSLogix/Invoke-FslShrinkDisk/tree/Optimize-OneDisk

And test?  Let me know how it goes.

Thanks

Jim

**Comment by gasjur** [comment]
Hello Patrick,
we had the same problem in our environment. The script works fine for fresh VDHX created by FSLogix itself - but runs into an Error for the VHDX that has been migrated from Citrix UPM Profile with the Citrix UPM to FSLogix Migration script from David Ott.
As Jim mentioned there is a difference in the disk type of those VHDX.
I have adapted the script so that it works regardless of whether the vhdx type is Basif or IFS. Because in a Migrated environment you will always have new fresh users with basic disks and old users with disk of the type IFS.

I have attached the modified script.

Regards
Jürgen


[Invoke-FslShrinkDisk.txt](https://github.com/FSLogix/Invoke-FslShrinkDisk/files/6041339/Invoke-FslShrinkDisk.txt)
