### ISSUE TITLE
SkippedAlreadyMinimum

### ISSUE THREAD

**Issue by ksimpson0** [FSLogix/Invoke-FslShrinkDisk#2]
I have a disk that is 626 MB. the actual size of data in the disk is 125 MB I run the script with -RatioFreeSpace 0.005 or even 0 and it still gives that error SkippedAlreadyMinimum. Am i misunderstanding how that parameter works?

**Comment by lordjeb** [comment]
I believe that the SkippedAlreadyMinimum error indicates that the partition size within the disk is already as small as it can go. This is probably because in addition to the data within the disk, there is a minimum amount of size required for file system structures.

**Comment by ksimpson0** [comment]
i went up to 1.8 GB disk and with 600 MG of data an it still fails that a lot of space required for system structure

**Comment by JimMoyle** [comment]
NTFS requires a size around 3GB for system structure.  You can see it by running NTFSINfo from sysinternals

**Comment by JimMoyle** [comment]
*If the max size is 30GB

**Comment by hmbooms** [comment]
@JimMoyle does that also apply to ReFS. I have the same issue. Profile.vhdx is 2GB but actual size is 600MB.

**Comment by JimMoyle** [comment]
@hmbooms Yes it applies exactly, as it's still NTFS inside the disk, it's immaterial what the filesystem is the is hosting the disk.

**Comment by hmbooms** [comment]
Ok thanks for the response.

**Comment by JimMoyle** [comment]
No worries, you can see the same behaviour by creating a dynamic vhdx in disk manager and then looking at the minimum size when you try and shrink.  It's not specifically an FSLogix problem, the underlying vhd(x) disk format would need to be updated.

**Comment by hmbooms** [comment]
Jim out of interest. See screenshot below. Where can I see what the minimum size is?

![image](https://user-images.githubusercontent.com/31475152/84897438-dbaf1b80-b0a5-11ea-95b7-e0bb27142d9f.png)

**Comment by JimMoyle** [comment]
The values in Red boxes are what you need, I've changed into MiB, this will be very close to the minimum size you can shrink to.  You can also look in the event log for ID 259 and it will say it's the $Bitmap::Data file which is preventing shrink (Bitmap::Data is part of the MFT)

![image](https://user-images.githubusercontent.com/20442811/84898001-73a90700-b09e-11ea-9023-33a616689285.png)

**Comment by JimMoyle** [comment]
The MFT zone only takes up a small amount of space on disk, but it prevents the shrink.

**Comment by hmbooms** [comment]
Great thanks for the explanation. I also tried to shrink it with Disk Management and got the following output.

![image](https://user-images.githubusercontent.com/31475152/84898385-74926680-b0a7-11ea-8c6c-82ee8230ad45.png)

Don't know if this is accurate.

**Comment by JimMoyle** [comment]
Yep exactly, 3122 is close enough to 3277 and you'll see this for any disk size (relative to max size).  You can do a funky workaround and create the disk with a tiny partition to start with (which places the MFT zone at the start) then extend the partition.  When you do NTFSInfo and Shrink through DiskManager this should show you a much smaller size.

**Comment by hmbooms** [comment]
@JimMoyle Could you clarify below result:

**Scenario:**
* Created Dynamic Virtual Disk (*.vhdx) size 10GB.
* Created Dummy file (1GB) copied and removed in the Dynamic Virtual Disk

**Scripts:**
1- Invoke-FslShrinkDisk (based on diskpart)
2- Invoke-CompactFSLDisk (based on Hyper-V  - http://www.citrixirc.com/?p=829)

**Result:**
_Script1_
![image](https://user-images.githubusercontent.com/31475152/84917767-09a15980-b0c0-11ea-9142-4b4e05e44c3c.png)


_Script 2_
![image](https://user-images.githubusercontent.com/31475152/84917657-e4ace680-b0bf-11ea-9fe3-ed127c351620.png)

**Conclusion:**
The Script 1 doesn't shrink the disk but the hyper-v does... Both Virtual Disk are identical.

Looking forward hearing from you...

**Comment by JimMoyle** [comment]
I'm not sure why you want me to comment on Davids tool.  It's a good tool.  I don't use Hyper-V module any more due to community feedback and I believe his is the same.  Though you'd have to ask him to be sure.

If you want more explanation of mine, the slab consolidation of the defrag in optimize-disk cmdlet is better than in defrag giving you the possibility of more shrinkage of the white space between the actual data and the MFT.  Which is why the numbers aren't exactly equal in the above as built-in defrag still gives you some slab consolidation.

The reason the community doesn't like Hyper-V is that it has a prerequisite for the Hyper-V role which isn't available in many circumstances.

I don't want to have two code paths to maintain which do almost exactly the same thing, as it's a fair bit more work for me.  This is in the code comments.

I'd be very happy to accept a pull request containing code to reliably use hyper-v when available and use the current code when not available and have a choice via switch to let the user choose if both could be used.

Jim

**Comment by hmbooms** [comment]
I was just wondering why there was a difference between the two script because what you are saying that the method is almost identical. I also do not prefer the Hyper-V module.

I did the same test with a 5GB Dynamic Virtual Disk and both scripts shrank the disk, but when I use a 10GB Dynamic Virtual Disk the output is different.

**Comment by JimMoyle** [comment]
There shouldn't be a difference between 5 and 10 GB, did you do the test in powershell or manually?

If you did it in pwsh, I'll retest this end

**Comment by hmbooms** [comment]
Both in PowerShell

**Comment by JimMoyle** [comment]
link to the code?

**Comment by hmbooms** [comment]
Script 1: [https://github.com/FSLogix/Invoke-FslShrinkDisk/blob/master/Invoke-FslShrinkDisk.ps1]
Script 2: [(https://pastebin.com/3qumGgF9)]

**Comment by JimMoyle** [comment]
Ahhh I meant the code you used to create the disks copy the file etc.

I'm not comparing my to to Davids btw that would seem pretty rude to me :)

**Comment by hmbooms** [comment]
Ohww sorry about that.. I just created a Dynamics Virtual Disk in Disk Management of Windows.

![image](https://user-images.githubusercontent.com/31475152/84943499-bc83ae80-b0e4-11ea-91c9-410e1eead11c.png)

After that I created a 1GB text file in command prompt.

echo "This is just a sample line appended to create a big file.. " > dummy.txt
for /L %i in (1,1,24) do type dummy.txt >> dummy.txt
